package com.github.kiulian.downloader.model.subtitles;

import com.github.clans.fab.BuildConfig;
import java.util.regex.Pattern;

/* loaded from: classes-dex2jar.jar:com/github/kiulian/downloader/model/subtitles/SubtitlesInfo.class */
public class SubtitlesInfo {
    private static final Pattern fmtRegex = Pattern.compile("&fmt=[^&]*");
    private static final Pattern tlangRegex = Pattern.compile("&tlang=[^&]*");
    private final boolean fromCaptions;
    private final boolean isAutoGenerated;
    private final String language;
    private final String url;

    public SubtitlesInfo(String str, String str2, boolean z) {
        this(str, str2, z, false);
    }

    public SubtitlesInfo(String str, String str2, boolean z, boolean z2) {
        this.url = tlangRegex.matcher(fmtRegex.matcher(str).replaceAll(BuildConfig.FLAVOR)).replaceAll(BuildConfig.FLAVOR);
        this.language = str2;
        this.isAutoGenerated = z;
        this.fromCaptions = z2;
    }

    public String getLanguage() {
        return this.language;
    }

    public String getUrl() {
        return this.url;
    }

    public boolean isAutoGenerated() {
        return this.isAutoGenerated;
    }

    public boolean isFromCaptions() {
        return this.fromCaptions;
    }
}
